version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saga-postgres
    environment:
      POSTGRES_DB: saga_development
      POSTGRES_USER: saga_user
      POSTGRES_PASSWORD: saga_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saga_user -d saga_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: saga-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: saga-postgres-test
    environment:
      POSTGRES_DB: saga_test
      POSTGRES_USER: saga_user
      POSTGRES_PASSWORD: saga_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    profiles:
      - test

volumes:
  postgres_data:
  postgres_test_data:
  redis_data: