'use client'

import { FurbridgeCard } from '@/components/ui/furbridge-card'
import { Badge } from '@/components/ui/badge'
import { BookOpen, Sparkles, Users, Clock } from 'lucide-react'

interface ChapterSummary {
  id: string
  chapter_number: number
  chapter_title: string
  ai_summary: string
  story_count: number
  total_duration: number
  created_at: string
  themes: string[]
  key_moments: string[]
}

interface ChapterSummaryCardProps {
  chapterSummary: ChapterSummary
  onClick?: () => void
}

export function ChapterSummaryCard({ chapterSummary, onClick }: ChapterSummaryCardProps) {
  const formatDuration = (totalSeconds: number) => {
    const hours = Math.floor(totalSeconds / 3600)
    const minutes = Math.floor((totalSeconds % 3600) / 60)
    
    if (hours > 0) {
      return `${hours}h ${minutes}m`
    }
    return `${minutes}m`
  }

  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', {
      month: 'long',
      year: 'numeric'
    })
  }

  return (
    <FurbridgeCard 
      className="p-6 bg-gradient-to-br from-furbridge-teal/5 to-furbridge-orange/5 border-2 border-furbridge-teal/20 hover:shadow-lg transition-all duration-300 cursor-pointer"
      onClick={onClick}
    >
      <div className="space-y-4">
        {/* Header */}
        <div className="flex items-start justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-12 h-12 bg-furbridge-teal/10 rounded-full flex items-center justify-center">
              <BookOpen className="h-6 w-6 text-furbridge-teal" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="text-xl font-bold text-gray-900">
                  Chapter {chapterSummary.chapter_number}
                </h3>
                <Badge className="bg-furbridge-teal text-white">
                  <Sparkles className="h-3 w-3 mr-1" />
                  AI Summary
                </Badge>
              </div>
              <h4 className="text-lg font-semibold text-furbridge-teal">
                {chapterSummary.chapter_title}
              </h4>
            </div>
          </div>
          
          <div className="text-right text-sm text-gray-600">
            <div>{formatDate(chapterSummary.created_at)}</div>
          </div>
        </div>

        {/* AI Summary */}
        <div className="space-y-3">
          <p className="text-gray-700 leading-relaxed">
            {chapterSummary.ai_summary}
          </p>
        </div>

        {/* Themes */}
        {chapterSummary.themes && chapterSummary.themes.length > 0 && (
          <div className="space-y-2">
            <h5 className="text-sm font-medium text-gray-900">Key Themes:</h5>
            <div className="flex flex-wrap gap-2">
              {chapterSummary.themes.map((theme, index) => (
                <Badge key={index} variant="outline" className="text-xs">
                  {theme}
                </Badge>
              ))}
            </div>
          </div>
        )}

        {/* Key Moments */}
        {chapterSummary.key_moments && chapterSummary.key_moments.length > 0 && (
          <div className="space-y-2">
            <h5 className="text-sm font-medium text-gray-900">Memorable Moments:</h5>
            <ul className="space-y-1">
              {chapterSummary.key_moments.slice(0, 3).map((moment, index) => (
                <li key={index} className="text-sm text-gray-600 flex items-start">
                  <span className="text-furbridge-orange mr-2 mt-1">•</span>
                  <span>{moment}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Stats */}
        <div className="flex items-center justify-between pt-3 border-t border-gray-200">
          <div className="flex items-center space-x-4 text-sm text-gray-600">
            <div className="flex items-center space-x-1">
              <Users className="h-4 w-4" />
              <span>{chapterSummary.story_count} stories</span>
            </div>
            <div className="flex items-center space-x-1">
              <Clock className="h-4 w-4" />
              <span>{formatDuration(chapterSummary.total_duration)}</span>
            </div>
          </div>
          
          <div className="text-xs text-gray-500">
            Generated by AI
          </div>
        </div>
      </div>
    </FurbridgeCard>
  )
}

export default ChapterSummaryCard
