/**
 * Image types for story and interaction images
 */

export interface StoryImage {
  id: string
  story_id: string
  transcript_id: string | null
  storage_path: string
  file_name: string
  file_size: number
  mime_type: string
  width: number | null
  height: number | null
  order_index: number
  is_primary: boolean
  source_type: 'transcript' | 'comment'
  source_interaction_id: string | null
  uploaded_by: string
  created_at: Date
  updated_at: Date
  url?: string // Temporary signed URL, generated by API
}

export interface InteractionImage {
  id: string
  interaction_id: string
  storage_path: string
  file_name: string
  file_size: number
  mime_type: string
  width: number | null
  height: number | null
  order_index: number
  uploaded_by: string
  created_at: Date
  updated_at: Date
  url?: string // Temporary signed URL, generated by API
}

// Request/Response types for API endpoints

export interface ImageUploadRequest {
  file: File
  transcript_id?: string
  interaction_id?: string
}

export interface ImageUploadResponse {
  image: StoryImage | InteractionImage
  url: string
}

export interface ImageReorderRequest {
  image_ids: string[] // Array of image IDs in new order
}

export interface SetPrimaryImageRequest {
  image_id: string
}

export interface CopyImagesFromCommentRequest {
  interaction_image_ids: string[] // Array of interaction image IDs to copy
}

export interface CopyImagesFromCommentResponse {
  images: StoryImage[]
}

// Validation constants
export const IMAGE_VALIDATION = {
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB in bytes
  MAX_IMAGES_PER_TRANSCRIPT: 6,
  MAX_IMAGES_PER_INTERACTION: 6,
  SUPPORTED_FORMATS: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'],
  SUPPORTED_EXTENSIONS: ['jpg', 'jpeg', 'png', 'gif', 'webp'],
  COMPRESSION_THRESHOLD: 2 * 1024 * 1024, // 2MB - compress images larger than this
  COMPRESSION_QUALITY: 0.8, // JPEG compression quality
} as const

// Error types
export type ImageUploadError =
  | 'INVALID_FORMAT'
  | 'FILE_TOO_LARGE'
  | 'TOO_MANY_IMAGES'
  | 'UPLOAD_FAILED'
  | 'PERMISSION_DENIED'
  | 'INVALID_REQUEST'

export interface ImageError {
  code: ImageUploadError
  message: string
  details?: string
}
