name: Minimal CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-shared-only:
    name: Test Shared Package Only
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run shared tests
        run: npm run test --workspace=packages/shared

      - name: Build shared package
        run: npm run build --workspace=packages/shared

  basic-validation:
    name: Basic Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate package.json files
        run: |
          echo "Validating package.json files..."
          node -e "console.log('Root package.json:', JSON.parse(require('fs').readFileSync('package.json', 'utf8')).name)"
          node -e "console.log('Backend package.json:', JSON.parse(require('fs').readFileSync('packages/backend/package.json', 'utf8')).name)"
          node -e "console.log('Web package.json:', JSON.parse(require('fs').readFileSync('packages/web/package.json', 'utf8')).name)"
          node -e "console.log('Mobile package.json:', JSON.parse(require('fs').readFileSync('packages/mobile/package.json', 'utf8')).name)"
          node -e "console.log('Shared package.json:', JSON.parse(require('fs').readFileSync('packages/shared/package.json', 'utf8')).name)"

      - name: Check basic file structure
        run: |
          echo "Checking basic file structure..."
          ls -la packages/
          ls -la packages/backend/src/
          ls -la packages/web/src/
          ls -la packages/mobile/src/
          ls -la packages/shared/src/