name: Simple CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test-backend-basic:
    name: Test Backend Basic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=packages/shared

      - name: Check backend package structure
        run: |
          echo "Checking backend package structure..."
          ls -la packages/backend/
          ls -la packages/backend/src/
          echo "Backend package.json exists: $(test -f packages/backend/package.json && echo 'YES' || echo 'NO')"

  test-web-basic:
    name: Test Web Basic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=packages/shared

      - name: Check web package structure
        run: |
          echo "Checking web package structure..."
          ls -la packages/web/
          ls -la packages/web/src/
          echo "Web package.json exists: $(test -f packages/web/package.json && echo 'YES' || echo 'NO')"

  test-mobile-basic:
    name: Test Mobile Basic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=packages/shared

      - name: Check mobile package structure
        run: |
          echo "Checking mobile package structure..."
          ls -la packages/mobile/
          ls -la packages/mobile/src/
          echo "Mobile package.json exists: $(test -f packages/mobile/package.json && echo 'YES' || echo 'NO')"

  test-shared:
    name: Test Shared Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run shared tests
        run: npm run test --workspace=packages/shared

  basic-validation:
    name: Basic Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate package.json files
        run: |
          echo "Validating package.json files..."
          node -e "console.log('Root package.json:', JSON.parse(require('fs').readFileSync('package.json', 'utf8')).name)"
          node -e "console.log('Backend package.json:', JSON.parse(require('fs').readFileSync('packages/backend/package.json', 'utf8')).name)"
          node -e "console.log('Web package.json:', JSON.parse(require('fs').readFileSync('packages/web/package.json', 'utf8')).name)"
          node -e "console.log('Mobile package.json:', JSON.parse(require('fs').readFileSync('packages/mobile/package.json', 'utf8')).name)"
          node -e "console.log('Shared package.json:', JSON.parse(require('fs').readFileSync('packages/shared/package.json', 'utf8')).name)"

      - name: Check basic file structure
        run: |
          echo "Checking basic file structure..."
          ls -la packages/
          ls -la packages/backend/src/
          ls -la packages/web/src/
          ls -la packages/mobile/src/
          ls -la packages/shared/src/