name: Sync Environment Variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'preview'
        type: choice
        options:
        - preview
        - production
      sync_supabase:
        description: 'Sync Supabase variables'
        required: false
        default: true
        type: boolean
      sync_stripe:
        description: 'Sync Stripe variables'
        required: false
        default: true
        type: boolean

jobs:
  sync-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Sync Supabase Environment Variables
        if: github.event.inputs.sync_supabase == 'true'
        run: |
          cd packages/web
          
          echo "🔧 Syncing Supabase environment variables to ${{ github.event.inputs.environment }}..."
          
          # Note: In a real scenario, these would come from GitHub secrets
          # For security, we're showing the structure but not actual values
          
          echo "NEXT_PUBLIC_SUPABASE_URL would be synced here"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY would be synced here"
          echo "SUPABASE_SERVICE_ROLE_KEY would be synced here"
          
          echo "✅ Supabase variables sync complete"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Sync Stripe Environment Variables
        if: github.event.inputs.sync_stripe == 'true'
        run: |
          cd packages/web
          
          echo "💳 Syncing Stripe environment variables to ${{ github.event.inputs.environment }}..."
          
          # Note: In a real scenario, these would come from GitHub secrets
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY would be synced here"
          echo "STRIPE_SECRET_KEY would be synced here"
          
          echo "✅ Stripe variables sync complete"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Verify Environment Configuration
        run: |
          echo "🔍 Environment configuration verification for ${{ github.event.inputs.environment }}:"
          echo "- Supabase: ${{ github.event.inputs.sync_supabase == 'true' && '✅ Synced' || '⏭️ Skipped' }}"
          echo "- Stripe: ${{ github.event.inputs.sync_stripe == 'true' && '✅ Synced' || '⏭️ Skipped' }}"
          echo "- Target: ${{ github.event.inputs.environment }}"

      - name: Trigger Deployment
        if: github.event.inputs.environment == 'production'
        run: |
          echo "🚀 Triggering production deployment after environment sync..."
          # This would trigger a new deployment to pick up the updated environment variables
